language: go

go:
- "1.10.x"

install:

before_install:
- go get -u github.com/alecthomas/gometalinter
- go get -u github.com/mattn/goveralls
- export PATH=$PATH:$GOPATH/bin
- gometalinter --install --update
- go generate -x ./...

script:
- travis_wait 30 go test ./... -v -covermode=count -coverprofile=coverage.out -timeout 100m

after_success:
- gometalinter -e bindata --deadline=1000s ./...
- goveralls -coverprofile=coverage.out -service=travis-ci
